# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Test with Maven
      run: mvn test --batch-mode
    - name: Run Sonar Analysis
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn -ntp --batch-mode initialize org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=anhitian-framework -Dsonar.organization=anhitian -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -Dgpg.skip -Dgithub
      env:
        GITHUB_TOKEN: ${{ github.token }}
